version: '2'
services:
  users-service:
    build: ./users-service
    links:
      - 'db:db'
    ports:
      - '8123:8123'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=DB
  db:
    build: ./test-database
